main: com.akutasan.SkinRoleComp
name: SkinRoleComp
version: 1.2
author: Akutasan

authors:
  - Timm
commands:
  skincomp:
    description: Start a skin competition!
  roleplay:
    description: Start a roleplay!
  eventtp:
    description: No permission!